### ISSUE TITLE
WGPURenderer compile error on startup

### ISSUE THREAD

**Issue by OmarShehata** [takahirox/online-wgsl-editor#15]
I'm using Chrome Canary

```
Version 100.0.4863.0 (Official Build) canary (64-bit)
```

I get the following error when I open https://takahirox.github.io/online-wgsl-editor/index.html

```
renderer.js:107 Uncaught (in promise) Error: Compile error
    at WGPURenderer.compile (renderer.js:107:13)
    at async App._updateShader (index.js:216:7)
    at async Function.create (index.js:89:5)
    at async run (index.html:152:17)
```

I also get the following warnings

```
10 warning(s) generated while compiling the shader:
:2:3 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
  [[builtin(position)]] position: vec4<f32>;
  ^^

:3:3 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
  [[location(1)]] normal: vec3<f32>;
  ^^

:4:3 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
  [[location(2)]] uv: vec2<f32>;
  ^^

:15:1 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
[[group(0), binding(0)]]
^^

:18:1 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
[[stage(vertex)]]
^^

:20:3 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
  [[location(0)]] position: vec3<f32>,
  ^^

:21:3 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
  [[location(1)]] normal: vec3<f32>,
  ^^

:22:3 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
  [[location(2)]] uv: vec2<f32>,
  ^^

:31:1 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
[[stage(fragment)]]
^^

:32:33 warning: use of deprecated language feature: [[decoration]] style decorations have been replaced with @decoration style
fn fs_main(in: VertexOutput) -> [[location(0)]] vec4<f32> {
```

Let me know if there is any other info I can provide. Thank you @takahirox for creating this awesome project! I saw it recently at the WebGPU meetup talk and was quite amazed.

**Comment by takahirox** [comment]
Thanks for the report.
We need to update the shader code to follow the latest WGSL spec.
I will update it soon.
